[workspace]
resolver = "2"
members = [
    "aoc*",
    "utils",
]
default-members = ["aoc2016"]

[workspace.dependencies]
md5 = "0.7.0"
regex = "1.10.2"
serde_json = "1.0.111"
utils = { path = "utils" }
